sudo: required
language: node_js

node_js: node

dist: trusty

jobs:
  include:
    - yarn install
    - yarn lint
    - yarn build --prefix-paths
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    - stage: deploy
      node_js: lts/*
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: public
        on:
          branch: master
