sudo: required
language: node_js

cache:
  directories:
    - node_modules

node_js: node

dist: trusty

jobs:
  include:
    - stage: release
      script: 
        - yarn lint
        - yarn build --prefix-paths
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    - stage: deploy
      if: branch = master
      node_js: lts/*
      script: yarn build --prefix-paths
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: public
        on:
          branch: master
